version: '3.8'

services:
    server:
        build:
            context: ./simpson-server
            dockerfile: Dockerfile
        image: laravel_app
        container_name: server
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8080:8080"
        command: bash -c "php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8080"
        networks:
            - laravel

    ui:
        build:
            context: ./simpson-ui
            dockerfile: Dockerfile
        image: angular_app
        container_name: ui
        depends_on:
            - server
        ports:
            - "8081:80"
        networks:
            - laravel

    db:
        image: postgres:17
        container_name: db
        restart: always
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            - laravel
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    laravel:
