version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        ports:
            - "8080:8080"
        command: php artisan serve --host=0.0.0.0 --port=8080
        networks:
            - laravel
        build:
            context: .
            dockerfile: Dockerfile

    db:
        image: postgres:17
        container_name: laravel_db
        restart: always
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            - laravel

networks:
    laravel:
